git:
  depth: false
jobs:
  include:
    - stage: tests
      name: Frontend Tests
      os: linux
      language: node_js
      node_js: 14
      addons:
        sonarcloud:
          organization: afrima
          token:
            - ${SONAR_TOKEN}
      before_install:
        - cd src/frontend
        - npm install -g yarn
      install:
        - yarn
      script:
        - npm run lint
        - npm run test
        - sonar-scanner
    - name: Backend Tests
      os: linux
      language: go
      go: 1.14
      addons:
        sonarcloud:
          organization: afrima
          token:
            - ${SONAR_TOKEN}
      before_install:
        - cd ../..
        - mv Afrima afrima
        - cd afrima/vocabulary_learning_helper/src/backend
      install:
        - go get -d -v
        - go get github.com/stretchr/testify
      script:
        - go test -coverprofile=coverage.out -coverpkg=./... ./...
        - sonar-scanner
    - stage: build
      os: linux
      services: docker
      script:
        - docker build -t ${DOCKER_USER}/vocabulary_trainer -f DockerfileForPi .
      after_success:
        - docker login -u=${DOCKER_USER} -p=${DOCKER_PASSWORD}
        - docker tag ${DOCKER_USER}/vocabulary_trainer ${DOCKER_USER}/vocabulary_trainer:latest
        - docker push ${DOCKER_USER}/vocabulary_trainer:latest
        - docker tag ${DOCKER_USER}/vocabulary_trainer ${DOCKER_USER}/vocabulary_trainer:${TRAVIS_BUILD_NUMBER}
        - docker push ${DOCKER_USER}/vocabulary_trainer:${TRAVIS_BUILD_NUMBER}
