git:
  depth: false
jobs:
  include:
    - stage: tests
      name: Frontend Tests
      addons:
        sonarcloud:
          organization: afrima
          token:
            - ${SONAR_TOKEN}
      language: node_js
      node_js: 12
      before_install:
        - cd src/frontend
        - npm install -g yarn
      install:
        - yarn
      script:
        - npm run lint
        - npm run test
        - sonar-scanner
    - name: Backend Tests
      addons:
        sonarcloud:
          organization: afrima
          token:
            - ${SONAR_TOKEN}
      language: go
      go: 1.14
      before_install:
        - cd src/backend
      install:
        - go get -d -v
        - go get github.com/stretchr/testify
      script:
        - go test -coverprofile=coverage.out -coverpkg=./... ./...
        - sonar-scanner
    - stage: build
      services: docker
      script:
        - docker build -t vocabulary_trainer -f DockerfileForPi .
      before_deploy:
        - docker login --username=${DOCKER_USER} --password=${DOCKER_PASSWORD}
        - docker tag "vocabulary_trainer" "vocabulary_trainer:latest"
        - docker tag "vocabulary_trainer" "vocabulary_trainer:${version}"
      deploy:
        provider: script
          script: docker push "vocabulary_trainer:latest" && docker push "vocabulary_trainer:${version}"
          on:
            branch: master