name: Build Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  yarn:
    name: Yarn
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache node_modules
      uses: actions/cache@v1
      id: yarn-cache-node-modules
      with:
        path: src/frontend/node_modules
        key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-cache-node-modules-
    - name: Yarn install
      if: steps.yarn-cache-node-modules.outputs.cache-hit != 'true'
      working-directory: ./src/frontend
      run: yarn install
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [yarn]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: lint
      working-directory: ./src/frontend
      run: npm run lint
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [yarn]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: test
      working-directory: ./src/frontend
      run: npm run test
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [yarn]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build
      working-directory: ./src/frontend
      run: npm run build:prod
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: src/frontend/dist 
